// Maps country name strings (as stored in shelf.json) to ISO 3166-1 alpha-2 codes,
// used to colour country paths in the world map SVG on /stats.
export const ISO_ALPHA2: Record<string, string> = {
  'Afghanistan': 'AF',
  'Argentina': 'AR',
  'Australia': 'AU',
  'Austria': 'AT',
  'Bosnia and Herzegovina': 'BA',
  'Brazil': 'BR',
  'Canada': 'CA',
  'Chile': 'CL',
  'China': 'CN',
  'Colombia': 'CO',
  'Cyprus': 'CY',
  'Czech Republic': 'CZ',
  'Dominican Republic': 'DO',
  'Egypt': 'EG',
  'France': 'FR',
  'Germany': 'DE',
  'Ghana': 'GH',
  'Greece': 'GR',
  'Guatemala': 'GT',
  'Hungary': 'HU',
  'India': 'IN',
  'Iran': 'IR',
  'Ireland': 'IE',
  'Israel': 'IL',
  'Italy': 'IT',
  'Japan': 'JP',
  'Lebanon': 'LB',
  'Mexico': 'MX',
  'Morocco': 'MA',
  'New Zealand': 'NZ',
  'Nigeria': 'NG',
  'Pakistan': 'PK',
  'Palestine': 'PS',
  'Poland': 'PL',
  'Russia': 'RU',
  'South Africa': 'ZA',
  'South Korea': 'KR',
  'Spain': 'ES',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Syria': 'SY',
  'Taiwan': 'TW',
  'Turkey': 'TR',
  'United Kingdom': 'GB',
  'United States': 'US',
  'Vietnam': 'VN',
};
